export const BOARD_RESET = "BOARD_RESET";
export const BOARD_SELECTEDAREA_SET_INI = "BOARD_SELECTEDAREA_SET_INI";
export const BOARD_SELECTEDAREA_SET_END = "BOARD_SELECTEDAREA_SET_END";

export const TILES_TOGGLE = "TILES_TOGGLE";
